[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
fuzz = { runs = 256 }
invariant = { runs = 128, depth = 32, fail_on_revert = false }

[profile.fork]
test = "fork-test"

[rpc_endpoints]
authorized = "${CGQA_FORK_RPC_URL}"

[fmt]
line_length = 100
