#!/usr/bin/env python3
"""Verify that the v1.1 report is generated by the pinned verifier and fixture.

Only machine-specific environment metadata and the input path are normalized
before regenerated-versus-committed comparison. Every scored result and
structured diagnostic must otherwise match exactly.
"""
from __future__ import annotations

import copy
import difflib
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

PROOF_DIR = Path(__file__).resolve().parent
VERIFIER = PROOF_DIR / "independent_bundle_verifier.py"
FIXTURE = PROOF_DIR / "bundle_vectors_v1.json"
COMMITTED_REPORT = PROOF_DIR / "report.json"

PINNED_VERIFIER_SHA256 = (
    "26446ec98f757eb369dc15de8d49bf32f5e625704ea0a435d53f768fc14fa16c"
)
PINNED_FIXTURE_SHA256 = (
    "b21c5a44a79d422d52857f03e2f3327d559c409e98c482b4664e1ab726327403"
)
PINNED_FIXTURE_BYTES = 104_579
PINNED_VECTOR_CONTRACT = "bundle_vectors_v1"
PINNED_VECTOR_REVISION = "bundle_vectors_v1.1"
EXPECTED_TOP_LEVEL_KEYS = {"cases", "environment", "input", "summary", "verifier"}
EXPECTED_CASE_KEYS = {
    "expected",
    "failure_details",
    "missing_required_failures",
    "name",
    "observed",
    "passed",
    "required_failures",
}
EXPECTED_FAILURE_KEYS = {"call_id", "detail", "node", "reason", "seq"}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def fail(message: str) -> int:
    print(f"FAIL: {message}", file=sys.stderr)
    return 1


def load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} does not contain a JSON object")
    return value


def normalized(report: dict[str, Any]) -> dict[str, Any]:
    value = copy.deepcopy(report)
    value.pop("environment", None)
    input_section = value.get("input")
    if isinstance(input_section, dict):
        input_section.pop("path", None)
    return value


def validate_report_shape(report: dict[str, Any], label: str) -> None:
    keys = set(report)
    if keys != EXPECTED_TOP_LEVEL_KEYS:
        raise ValueError(
            f"{label} top-level keys differ: "
            f"expected={sorted(EXPECTED_TOP_LEVEL_KEYS)}, got={sorted(keys)}"
        )

    cases = report.get("cases")
    if not isinstance(cases, list) or len(cases) != 12:
        raise ValueError(f"{label} must contain exactly 12 case reports")

    for case in cases:
        if not isinstance(case, dict):
            raise ValueError(f"{label} contains a non-object case report")
        case_keys = set(case)
        if case_keys != EXPECTED_CASE_KEYS:
            raise ValueError(
                f"{label} case {case.get('name')!r} keys differ: "
                f"expected={sorted(EXPECTED_CASE_KEYS)}, got={sorted(case_keys)}"
            )
        if "observed_failures" in case:
            raise ValueError(f"{label} contains superseded observed_failures rows")
        failures = case.get("failure_details")
        if not isinstance(failures, list):
            raise ValueError(f"{label} case {case.get('name')!r} has no failure_details list")
        for failure in failures:
            if not isinstance(failure, dict) or set(failure) != EXPECTED_FAILURE_KEYS:
                raise ValueError(
                    f"{label} case {case.get('name')!r} has malformed failure_details row"
                )

    input_section = report.get("input")
    if not isinstance(input_section, dict):
        raise ValueError(f"{label} has no input object")
    if input_section.get("contract") != PINNED_VECTOR_CONTRACT:
        raise ValueError(f"{label} has the wrong vector contract: {input_section!r}")
    if input_section.get("revision") != PINNED_VECTOR_REVISION:
        raise ValueError(f"{label} has the wrong vector revision: {input_section!r}")

    summary = report.get("summary")
    if summary != {"cases_passed": 12, "cases_total": 12, "passed": True}:
        raise ValueError(f"{label} summary is not the expected 12/12 PASS: {summary!r}")


def main() -> int:
    for path in (VERIFIER, FIXTURE, COMMITTED_REPORT):
        if not path.is_file():
            return fail(f"missing required artifact: {path}")

    verifier_sha = sha256(VERIFIER)
    if verifier_sha != PINNED_VERIFIER_SHA256:
        return fail(
            "verifier SHA-256 mismatch: "
            f"got {verifier_sha}, expected {PINNED_VERIFIER_SHA256}"
        )

    fixture_bytes = FIXTURE.stat().st_size
    fixture_sha = sha256(FIXTURE)
    if fixture_bytes != PINNED_FIXTURE_BYTES:
        return fail(
            f"fixture size mismatch: got {fixture_bytes}, expected {PINNED_FIXTURE_BYTES}"
        )
    if fixture_sha != PINNED_FIXTURE_SHA256:
        return fail(
            "fixture SHA-256 mismatch: "
            f"got {fixture_sha}, expected {PINNED_FIXTURE_SHA256}"
        )

    with tempfile.TemporaryDirectory(prefix="attenu-proof-") as temp_dir:
        generated_path = Path(temp_dir) / "report.json"
        completed = subprocess.run(
            [
                sys.executable,
                str(VERIFIER),
                str(FIXTURE),
                "--report",
                str(generated_path),
            ],
            cwd=PROOF_DIR,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if completed.returncode != 0:
            print(completed.stdout, file=sys.stderr, end="")
            print(completed.stderr, file=sys.stderr, end="")
            return fail(f"verifier exited {completed.returncode}")

        generated = load_json(generated_path)

    committed = load_json(COMMITTED_REPORT)

    try:
        validate_report_shape(generated, "generated report")
        validate_report_shape(committed, "committed report")
    except ValueError as exc:
        return fail(str(exc))

    generated_source_sha = generated.get("verifier", {}).get("source_sha256")
    committed_source_sha = committed.get("verifier", {}).get("source_sha256")
    if generated_source_sha != verifier_sha or committed_source_sha != verifier_sha:
        return fail(
            "report verifier.source_sha256 does not match the verifier file: "
            f"generated={generated_source_sha!r}, committed={committed_source_sha!r}, "
            f"actual={verifier_sha!r}"
        )

    expected = normalized(generated)
    actual = normalized(committed)
    if expected != actual:
        expected_text = json.dumps(expected, ensure_ascii=False, indent=2, sort_keys=True)
        actual_text = json.dumps(actual, ensure_ascii=False, indent=2, sort_keys=True)
        diff = "\n".join(
            difflib.unified_diff(
                actual_text.splitlines(),
                expected_text.splitlines(),
                fromfile="committed/report.json (normalized)",
                tofile="regenerated/report.json (normalized)",
                lineterm="",
            )
        )
        print(diff, file=sys.stderr)
        return fail("committed report differs from regenerated verifier output")

    print("PASS: report provenance verified")
    print(f"verifier_sha256={verifier_sha}")
    print(f"fixture_bytes={fixture_bytes}")
    print(f"fixture_sha256={fixture_sha}")
    print(f"report_sha256={sha256(COMMITTED_REPORT)}")
    print("cases=12/12")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
