#!/usr/bin/env python3
"""Verify that the v1.2 report is generated by the pinned verifier and fixture.

Only machine-specific environment metadata and the input path are normalized
before regenerated-versus-committed comparison. Every scored result and
structured diagnostic must otherwise match exactly.
"""
from __future__ import annotations

import copy
import difflib
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

PROOF_DIR = Path(__file__).resolve().parent
VERIFIER = PROOF_DIR / "independent_bundle_verifier.py"
FIXTURE = PROOF_DIR / "bundle_vectors_v1.json"
COMMITTED_REPORT = PROOF_DIR / "report.json"

PINNED_VERIFIER_SHA256 = (
    "ad229ed3074b2c9dfd502beac4eb4ce9929c036946ebbf75bd46451016d412dd"
)
PINNED_FIXTURE_SHA256 = (
    "54311d68c8342c01ce233f4b1aea251125a4f3323fd9776c01843d3b2f5700ea"
)
PINNED_FIXTURE_BYTES = 146_765
PINNED_REVISION = "bundle_vectors_v1.2"
EXPECTED_CASE_NAMES = [
    "valid_bundle_v2",
    "reject_params_mismatch",
    "reject_outcome_without_allow",
    "reject_outcome_before_allow",
    "reject_duplicate_outcome",
    "reject_duplicate_call_id",
    "reject_rehashed_chain",
    "reject_tampered_entry",
    "reject_widened_scope",
    "reject_uncontained_allow",
    "reject_increased_ttl",
    "reject_loosened_ceiling",
    "valid_bundle_v2_literal",
    "reject_increased_ttl_literal",
    "reject_loosened_ceiling_literal",
    "reject_null_ttl_literal",
    "reject_omitted_ceiling_literal",
]
EXPECTED_TOP_LEVEL_KEYS = {
    "cases",
    "environment",
    "input",
    "repository_subject",
    "summary",
    "verifier",
}
EXPECTED_INPUT_KEYS = {"bytes", "contract", "path", "pinned_sha256", "revision", "sha256"}
EXPECTED_CASE_KEYS = {
    "expected",
    "failure_details",
    "missing_required_failures",
    "name",
    "observed",
    "passed",
    "required_failures",
}
EXPECTED_FAILURE_KEYS = {"call_id", "detail", "node", "reason", "seq"}
EXPECTED_REPOSITORY_SUBJECT = {
    "repository": "safal207/ContractGraph-QA",
    "pull_request": 152,
    "branch": "proof/attenu-guard-v0.12.1-independent",
    "receipt_url": (
        "https://github.com/safal207/ContractGraph-QA/pull/152"
        "#issuecomment-5528155565"
    ),
    "binding": "external receipt binds the exact base, head, and tree",
}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def fail(message: str) -> int:
    print(f"FAIL: {message}", file=sys.stderr)
    return 1


def load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} does not contain a JSON object")
    return value


def normalized(report: dict[str, Any]) -> dict[str, Any]:
    value = copy.deepcopy(report)
    value.pop("environment", None)
    input_section = value.get("input")
    if isinstance(input_section, dict):
        input_section.pop("path", None)
    return value


def validate_report_shape(report: dict[str, Any], label: str) -> None:
    keys = set(report)
    if keys != EXPECTED_TOP_LEVEL_KEYS:
        raise ValueError(
            f"{label} top-level keys differ: "
            f"expected={sorted(EXPECTED_TOP_LEVEL_KEYS)}, got={sorted(keys)}"
        )

    cases = report.get("cases")
    if not isinstance(cases, list) or len(cases) != 17:
        raise ValueError(f"{label} must contain exactly 17 case reports")
    names = [case.get("name") for case in cases if isinstance(case, dict)]
    if names != EXPECTED_CASE_NAMES:
        raise ValueError(f"{label} case list/order differs: {names!r}")

    for case in cases:
        if not isinstance(case, dict):
            raise ValueError(f"{label} contains a non-object case report")
        case_keys = set(case)
        if case_keys != EXPECTED_CASE_KEYS:
            raise ValueError(
                f"{label} case {case.get('name')!r} keys differ: "
                f"expected={sorted(EXPECTED_CASE_KEYS)}, got={sorted(case_keys)}"
            )
        if "observed_failures" in case:
            raise ValueError(f"{label} contains superseded observed_failures rows")
        failures = case.get("failure_details")
        if not isinstance(failures, list):
            raise ValueError(f"{label} case {case.get('name')!r} has no failure_details list")
        for failure in failures:
            if not isinstance(failure, dict) or set(failure) != EXPECTED_FAILURE_KEYS:
                raise ValueError(
                    f"{label} case {case.get('name')!r} has malformed failure_details row"
                )

    input_section = report.get("input")
    if not isinstance(input_section, dict) or set(input_section) != EXPECTED_INPUT_KEYS:
        raise ValueError(f"{label} input section has an unexpected shape")
    expected_input = {
        "bytes": PINNED_FIXTURE_BYTES,
        "contract": "bundle_vectors_v1",
        "pinned_sha256": PINNED_FIXTURE_SHA256,
        "revision": PINNED_REVISION,
        "sha256": PINNED_FIXTURE_SHA256,
    }
    observed_input = {key: value for key, value in input_section.items() if key != "path"}
    if observed_input != expected_input:
        raise ValueError(f"{label} input identity differs: {observed_input!r}")

    verifier = report.get("verifier")
    if not isinstance(verifier, dict):
        raise ValueError(f"{label} verifier section is missing")
    if verifier.get("id") != "safal207-independent-bundle-v1.2" or verifier.get("version") != "0.3.1":
        raise ValueError(f"{label} verifier identity differs: {verifier!r}")

    if report.get("repository_subject") != EXPECTED_REPOSITORY_SUBJECT:
        raise ValueError(f"{label} repository subject receipt differs")

    summary = report.get("summary")
    if summary != {"cases_passed": 17, "cases_total": 17, "passed": True}:
        raise ValueError(f"{label} summary is not the expected 17/17 PASS: {summary!r}")


def main() -> int:
    for path in (VERIFIER, FIXTURE, COMMITTED_REPORT):
        if not path.is_file():
            return fail(f"missing required artifact: {path}")

    verifier_sha = sha256(VERIFIER)
    if verifier_sha != PINNED_VERIFIER_SHA256:
        return fail(
            "verifier SHA-256 mismatch: "
            f"got {verifier_sha}, expected {PINNED_VERIFIER_SHA256}"
        )

    fixture_bytes = FIXTURE.stat().st_size
    fixture_sha = sha256(FIXTURE)
    if fixture_bytes != PINNED_FIXTURE_BYTES:
        return fail(
            f"fixture size mismatch: got {fixture_bytes}, expected {PINNED_FIXTURE_BYTES}"
        )
    if fixture_sha != PINNED_FIXTURE_SHA256:
        return fail(
            "fixture SHA-256 mismatch: "
            f"got {fixture_sha}, expected {PINNED_FIXTURE_SHA256}"
        )

    with tempfile.TemporaryDirectory(prefix="attenu-proof-") as temp_dir:
        generated_path = Path(temp_dir) / "report.json"
        completed = subprocess.run(
            [
                sys.executable,
                str(VERIFIER),
                str(FIXTURE),
                "--report",
                str(generated_path),
            ],
            cwd=PROOF_DIR,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if completed.returncode != 0:
            print(completed.stdout, file=sys.stderr, end="")
            print(completed.stderr, file=sys.stderr, end="")
            return fail(f"verifier exited {completed.returncode}")

        generated = load_json(generated_path)

    committed = load_json(COMMITTED_REPORT)

    try:
        validate_report_shape(generated, "generated report")
        validate_report_shape(committed, "committed report")
    except ValueError as exc:
        return fail(str(exc))

    generated_source_sha = generated.get("verifier", {}).get("source_sha256")
    committed_source_sha = committed.get("verifier", {}).get("source_sha256")
    if generated_source_sha != verifier_sha or committed_source_sha != verifier_sha:
        return fail(
            "report verifier.source_sha256 does not match the verifier file: "
            f"generated={generated_source_sha!r}, committed={committed_source_sha!r}, "
            f"actual={verifier_sha!r}"
        )

    expected = normalized(generated)
    actual = normalized(committed)
    if expected != actual:
        expected_text = json.dumps(expected, ensure_ascii=False, indent=2, sort_keys=True)
        actual_text = json.dumps(actual, ensure_ascii=False, indent=2, sort_keys=True)
        diff = "\n".join(
            difflib.unified_diff(
                actual_text.splitlines(),
                expected_text.splitlines(),
                fromfile="committed/report.json (normalized)",
                tofile="regenerated/report.json (normalized)",
                lineterm="",
            )
        )
        print(diff, file=sys.stderr)
        return fail("committed report differs from regenerated verifier output")

    print("PASS: report provenance verified")
    print(f"verifier_sha256={verifier_sha}")
    print(f"fixture_bytes={fixture_bytes}")
    print(f"fixture_sha256={fixture_sha}")
    print(f"report_sha256={sha256(COMMITTED_REPORT)}")
    print("revision=bundle_vectors_v1.2")
    print("cases=17/17")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
